### ISSUE TITLE
[feature request] keybind to swap single hotbar slot

### ISSUE THREAD

**Issue by yesn0t** [nyuppo/hotbarcycle#1]
hello, thanks for making this mod !  
if it's within the scope of this project, i hope you consider a separate keybind to cycle only one slot instead of the whole hotbar.  
(yesterday i saw [InventoryControlKeys](https://github.com/LothrazarMinecraftMods/InventoryControlKeys) and wished there was a updated alternative to that mod, so needless to say i can't wait to try hotbarswap !)

**Comment by nyuppo** [comment]
That's a great idea! I'll add that ASAP.

**Comment by nyuppo** [comment]
Just added in version 1.0.1. Should be updated on Modrinth soon, and Curseforge within the next couple days when it gets approved.

**Comment by yesn0t** [comment]
wow, that was quick, thank you !
