### ISSUE TITLE
Failed to load config in Mod Menu

### ISSUE THREAD

**Issue by ActualBest** [nyuppo/hotbarcycle#13]
![image](https://github.com/nyuppo/hotbarcycle/assets/78813556/5301d467-3d15-45af-9fb8-237abe81f762)

**Comment by nyuppo** [comment]
Do you have cloth config installed as well?

**Comment by ActualBest** [comment]
That was the issue. I missed it because it wasn't listed in the dependencies for 1.21. Thanks.
