### ISSUE TITLE
Interoperability with Inventory Profiles Next

### ISSUE THREAD

**Issue by blackd** [nyuppo/hotbarcycle#2]
Hi,

I've been getting some requests about making our 2 mods playing well together. Even some suggestions to just copy your features... which I don't want to do.

But I have to agree that both mods compliment each other features very well.
So if you are interested in making them compatible can you please contact me on discord https://discord.gg/23YCxmveUM

**Comment by nyuppo** [comment]
Heyo, I would love to add compatibility between our mods!

I joined that server, my discord is nyuppo#7534 if you wanted to DM me and discuss the problem.

Thanks!
