### ISSUE TITLE
[Feature Request] Reverse swap hotbar/slot

### ISSUE THREAD

**Issue by ghost** [nyuppo/hotbarcycle#3]
Hello, I usually only use the bottom 2 rows of my inventory for my hotbar and i'd like a keybind to just swap those two rows instead of the whole inventory.
Or you could also implement a keybind/modifier key to just reverse the order.

Thank you for the mod.

**Comment by nyuppo** [comment]
Heyo,
I'm planning a mini-rewrite for the 1.19 update to address an imcompatability with another mod, so I'll add config support as well that'll let you both reverse the order and configure with rows to include in the cycling :)

So if you can be patient for a little longer then I'll add these!

**Comment by ghost** [comment]
That's perfectly acceptable, I come from a different mod because it stopped being updated.
Good luck and thank you.

**Comment by nyuppo** [comment]
Implemented as a config option, use cloth config + mod menu 👍
