### ISSUE TITLE
[Feature Request] Swap with Scroll While use Modifier Key

### ISSUE THREAD

**Issue by ardissaps** [nyuppo/hotbarcycle#5]
Swap with Scroll Whel while use Modifier Key. As example hold H while scrolling instead of just H, same apply with single slot.
Thank you very much!!

**Comment by nyuppo** [comment]
Heyo! This feature will be added as a config option in the next update, coming very soon :)

**Comment by ardissaps** [comment]
> Heyo! This feature will be added as a config option in the next update, coming very soon :)

Nice to hear

**Comment by nyuppo** [comment]
Implemented as a config option, use cloth config + mod menu 👍

**Comment by ardissaps** [comment]
> Implemented as a config option, use cloth config + mod menu 👍 

Thank you very much! :)
