### ISSUE TITLE
Inventory Profiles next issue

### ISSUE THREAD

**Issue by Jordanisjord** [nyuppo/hotbarcycle#6]
For example if I have four tools on my hotbar when I cycle they get moved into different slots or even completely different inventory spots. Im not sure if that explains it better. 

I figured out its inventory profiles next that causes this to happen. Im playing on 1.18.2 so im guessing that version of this mod is not compatible.

**Comment by nyuppo** [comment]
Hi, sorry for the late reply:

Compatibility with Inventory Profiles Next was only added in the 1.19 update, however I may backport these changes to 1.18.2 at some point if the demand is high enough (or if I have some extra time lol)
